[package]
name = "winreg"
version = "0.4.0"
authors = ["Igor Shaula <gentoo90@gmail.com>"]
license = "MIT"
description = "Rust bindings to MS Windows Registry API"
repository = "https://github.com/gentoo90/winreg-rs"
documentation = "https://gentoo90.github.io/winreg-rs/v0.4.0/winreg/"
readme = "README.md"
keywords = ["Windows", "WinSDK", "Registry"]

[dependencies]
winapi = "0.2"
kernel32-sys = "0.2"
advapi32-sys = "0.2"
ktmw32-sys = { version = "0.1", optional = true }
rustc-serialize = { version = "0.3.19", optional = true }
serde = { version = "0.9.6", optional = true }
clippy = { version = "^0", optional = true }

[dev-dependencies]
rand = "0.3"
serde_derive = "0.9.6"

[features]
default = ["transactions", "serialization-rustc"]
transactions = ["ktmw32-sys"]
serialization-rustc = ["transactions", "rustc-serialize"]
serialization-serde = ["transactions", "serde"]
