[package]
name = "winreg"
version = "0.0.1"
authors = ["Igor Shaula <gentoo90@gmail.com>"]
license = "MIT"
description = "Rust bindings to MS Windows Registry API"

[dependencies]
winapi = "*"
advapi32-sys = "*"
