[package]
name = "winreg_example_serialization"
version = "0.1.0"
authors = ["Igor Shaula <gentoo90@gmail.com>"]
publish = false

[dependencies]
winreg = { path = "../../", features = ["serialization-rustc"] }
rustc-serialize = "0.3.19"
