name: CI
on:
  - push
jobs:
  tests:
    name: CI
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        channel: [1.31.1, stable]
    env:
      RUST_BACKTRACE: full
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust Stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.channel }}
          profile: minimal
          override: true
      - name: Cache cargo registry
        uses: actions/cache@v2
        continue-on-error: true
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --no-default-features
